### ISSUE TITLE
Assertion Failed: Engine parent failed to lookup 'service:user-session' dependency

### ISSUE THREAD

**Issue by dmtask** [ember-engines/ember-engines#293]
I created an ember engine app in #282. This also sounds almost, up to 2 problems. One is treated in the other issue, that others I would like to explain here.

I get the following error when calling the engine:
```
Assertion Failed: Engine parent failed to lookup 'service:user-session' dependency, as declared in 'engines.thingyFrontend.dependencies.services'.
Error
    at assert (http://localhost:4200/assets/vendor.js:16268:13)
    at assert (http://localhost:4200/assets/vendor.js:27196:34)
    at http://localhost:4200/assets/vendor.js:90714:23
    at Array.forEach (native)
    at http://localhost:4200/assets/vendor.js:90694:30
    at http://localhost:4200/assets/vendor.js:90725:15
    at Class.buildChildEngineInstance (http://localhost:4200/assets/vendor.js:90731:11)
    at Class.superWrapper [as buildChildEngineInstance] (http://localhost:4200/assets/vendor.js:50189:22)
    at Class._constructEngineInstance (http://localhost:4200/assets/vendor.js:91185:34)
    at http://localhost:4200/assets/vendor.js:91154:23
```

Engine (`addon/engine.js`):
```
import Engine from 'ember-engines/engine';
import Resolver from 'ember-resolver';
import loadInitializers from 'ember-load-initializers';
import config from './config/environment';

const { modulePrefix } = config;

const Eng = Engine.extend({
  modulePrefix,
  Resolver,
    dependencies: {
        services: [
            'session'
        ]
    }
});

loadInitializers(Eng, modulePrefix);

export default Eng;
```

App (`app/app.js`):
```
import Ember from 'ember';
import Resolver from './resolver';
import loadInitializers from 'ember-load-initializers';
import config from './config/environment';

let App;

Ember.MODEL_FACTORY_INJECTIONS = true;

App = Ember.Application.extend({
  modulePrefix: config.modulePrefix,
  podModulePrefix: config.podModulePrefix,
  Resolver,
    engines: {
        thingyFrontend: {
            dependencies: {
                services: [
                    {'session': 'user-session'}
                ]
            }
        }
    }
});

loadInitializers(App, config.modulePrefix);

export default App;
```

I have no idea why this error comes. Can someone help me?

**Comment by trentmwillis** [comment]
Looks like the host application can't find the `user-session` service when creating the Engine instance. Is the `user-session` service working in the host application normally? Can't tell much more without seeing more of the codebase.

**Comment by dmtask** [comment]
You can see the full code on the github Repos.
Engine: https://github.com/phortx/ember-engines-engine
App: https://github.com/phortx/ember-engines-app

I think you got me on the right idea. I did not think about the app, it's now running. Thanks for the tip. :)
