### ISSUE TITLE
'asset.replace is not a function' when engine has dependencies defined

### ISSUE THREAD

**Issue by IgorKvasn** [ember-engines/ember-engines#343]
Hi,
I created a simple ember app with engine. I added _ember-moment_ as a dependency in both main app and engine as well.
When I now run ember-cli, I get this error:

> TypeError: asset.replace is not a function
>     at Class.import (/home/user/Data/engines-deps/node_modules/ember-engines/lib/engine-addon.js:241:17)
>     at Class.importBrowserDependencies (/home/user/Data/engines-deps/node_modules/ember-cli-moment-shim/index.js:74:17)

I found a similar issue here #280, but it looks like the problem I am experiencing is not the same, because in my case I have no environment specific assets.

I created a simple [repo here](https://github.com/IgorKvasn/ember-engines-deps) - just run `ember s` to see the error.

However I am also not sure if I defined the dependency correctly - in the main app I put ember-moment under "devDependencies" and in engine under "dependencies"

**Comment by LBKinson** [comment]
I'm having this identical problem, also with the `ember-moment` addon

**Comment by IgorKvasn** [comment]
I also tried `ember-simple-auth ` instead of `ember-moment` - it didn't work either, so it's not addon's problem

**Comment by IgorKvasn** [comment]
I noticed that addons that don't have any 3rd party dependencies work fine

**Comment by rwjblue** [comment]
The issue is with addons that call `app.import` or `this.import` with an object instead of a string. See [here](https://github.com/jasonmit/ember-cli-moment-shim/blob/master/index.js#L74-L77). https://github.com/ember-engines/ember-engines/pull/252 would address this, but needs some tweaks...

**Comment by DegreeDev** [comment]
I have a temporary workaround for this issue: 

https://github.com/ember-engines/ember-engines/issues/343

This is not permanent fix and will be resolved by:  https://github.com/ember-engines/ember-engines/pull/252
