### ISSUE TITLE
Issue with addons who have images to import

### ISSUE THREAD

**Issue by brunowego** [ember-engines/ember-engines#348]
![5152157159_5ba65100a9_z](https://cloud.githubusercontent.com/assets/441774/23342309/ddc4ad08-fc36-11e6-8c53-33ad7a474a0d.jpg)

My addon has an image to import and when I try install inside a engine, I get a error.

#### Output Error

```sh
Funnel (Funnel
  vendor/images
  assets/images
 include:2): Expected Broccoli node, got undefined for inputNodes[0]
TypeError: Funnel (Funnel
  vendor/images
  assets/images
 include:2): Expected Broccoli node, got undefined for inputNodes[0]
    at Funnel.Plugin (/secret/node_modules/broccoli-plugin/index.js:23:13)
    at new Funnel (/secret/node_modules/broccoli-funnel/index.js:58:10)
    at funnelReducer.map.options (/secret/node_modules/ember-cli/lib/broccoli/ember-app.js:1490:12)
    at Array.map (native)
    at Class.EmberApp.otherAssets (/secret/node_modules/ember-cli/lib/broccoli/ember-app.js:1484:61)
    at Class.treeForPublic (/secret/node_modules/ember-engines/lib/engine-addon.js:531:30)
    at Class._treeFor (/secret/node_modules/ember-cli/lib/models/addon.js:517:33)
    at Class.treeFor (/secret/node_modules/ember-engines/lib/engine-addon.js:715:23)
    at project.addons.map.addon (/secret/node_modules/ember-cli/lib/broccoli/ember-app.js:525:20)
    at Array.map (native)
```

#### Versions

```
broccoli-asset-rev v2.5.0
ember-engines 0.5.0-beta.9
```

**Comment by brunowego** [comment]
Sorry, now I understand the issue. I find similar issue here https://github.com/martndemus/ember-font-awesome/commit/0cc6d0acd0883b3c447510fb0956ccdb416727ae.

**Comment by brunowego** [comment]
The issue persists. If I add inside the engine the (through `package.json`) I get the error.

**Comment by brunowego** [comment]
Fixed with:

```js
/* eslint-env node */
'use strict';

const Funnel = require('broccoli-funnel');
const mergeTrees = require('broccoli-merge-trees');
const join = require('path').join;

module.exports = {
  name: 'ember-cli-navbar',

  treeForPublic: function() {
    const imagesDir = new Funnel(join(this.root, 'vendor/images'), {
      include: ['*.svg'],
      destDir: '/assets/images'
    });

    return mergeTrees([imagesDir]);
  }
};
```
