### ISSUE TITLE
ember-cli-sass broken on ember-engines 0.5.0

### ISSUE THREAD

**Issue by rwwagner90** [ember-engines/ember-engines#378]
To reproduce, all you have to do is install both ember-cli-sass and ember-engines and do `ember s`. I put together a repo that you can just pull to see the problem. It complains there is no `addon.scss`, but you should be able to use `app/styles` and not have to have `addon.scss`.

https://github.com/rwwagner90/engine-sass-test

Possibly related to #376 

Stack trace:

```
The Broccoli Plugin: [SassCompiler] failed with:
Error: File not found: /addon.scss
in any of the following include paths:
  /Users/wagner5/engine-sass-test/tmp/sass_compiler-input_base_path-PwQhZA67.tmp
    at Object.findFileSync (/Users/wagner5/engine-sass-test/node_modules/include-path-searcher/index.js:12:9)
    at SassCompiler.build (/Users/wagner5/engine-sass-test/node_modules/broccoli-sass-source-maps/index.js:63:31)
    at /Users/wagner5/engine-sass-test/node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/index.js:149:21
    at tryCatch (/Users/wagner5/engine-sass-test/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/Users/wagner5/engine-sass-test/node_modules/rsvp/dist/rsvp.js:554:13)
    at publish (/Users/wagner5/engine-sass-test/node_modules/rsvp/dist/rsvp.js:522:7)
    at flush (/Users/wagner5/engine-sass-test/node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at SassCompiler.Plugin (/Users/wagner5/engine-sass-test/node_modules/broccoli-plugin/index.js:7:31)
    at SassCompiler.CachingWriter [as constructor] (/Users/wagner5/engine-sass-test/node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/index.js:18:10)
    at new SassCompiler (/Users/wagner5/engine-sass-test/node_modules/broccoli-sass-source-maps/index.js:20:17)
    at /Users/wagner5/engine-sass-test/node_modules/ember-cli-sass/index.js:38:12
    at Array.map (native)
    at SASSPlugin.toTree (/Users/wagner5/engine-sass-test/node_modules/ember-cli-sass/index.js:35:34)
    at /Users/wagner5/engine-sass-test/node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (/Users/wagner5/engine-sass-test/node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
    at module.exports.preprocessCss (/Users/wagner5/engine-sass-test/node_modules/ember-cli-preprocess-registry/preprocessors.js:148:10)
```

**Comment by rwwagner90** [comment]
As suggested by @rwjblue, we moved our styles to `addon/styles/addon.scss` instead, and everything works great. It was apparently a bug that it worked with them in the `app` directory.

Thanks @rwjblue! As always the 🍺 count owed increases 😄

**Comment by alexander-alvarez** [comment]
can we confirm what is causing this or how to debug it further? I've moved all of our in-repo engines styles from `app/styles` to `addon/styles` and still getting the error illustrated above. On engines 0.5.0, ember-cli 2.12.1
<details><summary>Logs</summary>

I renamed my engine to `in-repo-engine`

```
  broccoli-funnel:Funnel build, { in: '1ms', linkedRoots: true, inputPath: './tmp/funnel-input_base_path-To5pJ5fX.tmp', destPath: './tmp/funnel-output_path-AsnZwxRq.tmp/modules' } +2ms
  broccoli-funnel:Funnel: Addon#treeForStyles (ember-basic-dropdown) build, { in: '1ms', linkedRoots: true, inputPath: './tmp/funnel-input_base_path-6Ncvpd7V.tmp', destPath: './tmp/funnel-output_path-vbW6X2FM.tmp/app/styles' } +3ms
  broccoli-funnel:Funnel: Addon#treeForStyles (ember-power-select) build, { in: '1ms', linkedRoots: true, inputPath: './tmp/funnel-input_base_path-SDRQFoTJ.tmp', destPath: './tmp/funnel-output_path-b1lxgXV7.tmp/app/styles' } +1ms
  broccoli-funnel:Funnel: Addon#treeForStyles (ember-modal-dialog) build, { in: '1ms', linkedRoots: true, inputPath: './tmp/funnel-input_base_path-c3peOGEA.tmp', destPath: './tmp/funnel-output_path-8QsG4OTv.tmp/app/styles' } +1ms
  broccoli-funnel:Funnel: Addon#treeForStyles (ember-power-calendar) build, { in: '1ms', linkedRoots: true, inputPath: './tmp/funnel-input_base_path-oQK6NzGc.tmp', destPath: './tmp/funnel-output_path-fZth9s4K.tmp/app/styles' } +1ms
  broccoli-funnel:Funnel: Funnel: relocate app/styles for (in-repo-engine) build, { in: '0ms', linkedRoots: true, inputPath: './tmp/funnel-input_base_path-tmDXENyM.tmp/app/styles', destPath: './tmp/funnel-output_path-4hQi9GJu.tmp' } +1ms
  broccoli-sane-watcher [BroccoliMergeTrees#7831 -> WatchedDir#7847 -> ./lib/in-repo-engine/addon/styles#7848] addWatchDir: ./lib/in-repo-engine/addon/styles +0ms
  broccoli-caching-writer:SassCompiler walking undefined +20ms
  broccoli-caching-writer:SassCompiler { stats: 0, files: 12, inputPaths: [ './tmp/sass_compiler-input_base_path-Pc7jqXAA.tmp' ] } +1ms
  broccoli-caching-writer:SassCompiler derive cacheKey in 1ms +0ms
  broccoli-caching-writer:SassCompiler purge output in 2ms +2ms
  broccoli-caching-writer:SassCompiler rebuilding cache in 1ms +1ms
  broccoli-sane-watcher [BroccoliMergeTrees#7692 -> BroccoliMergeTrees#7829 -> SassCompiler#7830] triggerError [Error: The Broccoli Plugin: [SassCompiler] failed with:] +3ms
  ember-cli:watcher [BroccoliMergeTrees#7692 -> BroccoliMergeTrees#7829 -> SassCompiler#7830] didError [Error: The Broccoli Plugin: [SassCompiler] failed with:] +1ms
The Broccoli Plugin: [SassCompiler] failed with:
Error: File not found: /addon.scss
in any of the following include paths:
  ./tmp/sass_compiler-input_base_path-Pc7jqXAA.tmp
  at Object.findFileSync (./node_modules/include-path-searcher/index.js:12:9)
  at SassCompiler.build (./node_modules/broccoli-sass-source-maps/index.js:63:31)
  at ./node_modules/broccoli-caching-writer/index.js:149:21
  at tryCatch (./node_modules/rsvp/dist/rsvp.js:539:12)
  at invokeCallback (./node_modules/rsvp/dist/rsvp.js:554:13)
  at publish (./node_modules/rsvp/dist/rsvp.js:522:7)
  at flush (./node_modules/rsvp/dist/rsvp.js:2414:5)
  at nextTickCallbackWith0Args (node.js:436:9)
  at process._tickCallback (node.js:365:13)


The broccoli plugin was instantiated at: 
  at SassCompiler.Plugin (./node_modules/broccoli-plugin/index.js:7:31)
  at SassCompiler.CachingWriter [as constructor] (./node_modules/broccoli-caching-writer/index.js:18:10)
  at new SassCompiler (./node_modules/broccoli-sass-source-maps/index.js:20:17)
  at ./node_modules/ember-cli-sass/index.js:38:12
  at Array.map (native)
  at SASSPlugin.toTree (./node_modules/ember-cli-sass/index.js:35:34)
  at ./node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
  at Array.forEach (native)
  at processPlugins (./node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
  at module.exports.preprocessCss (./node_modules/ember-cli-preprocess-registry/preprocessors.js:148:10)
  at Class.compileStyles (./node_modules/ember-cli/lib/models/addon.js:788:33)
  at Class.treeForAddon (./node_modules/ember-engines/lib/engine-addon.js:393:42)
  at Class._treeFor (./node_modules/ember-cli/lib/models/addon.js:517:33)
  at Class.treeFor (./node_modules/ember-engines/lib/engine-addon.js:737:23)
  at ./node_modules/ember-cli/lib/broccoli/ember-app.js:525:20
  at Array.map (native)
  at EmberApp._notifyAddonIncluded.EmberApp.addonTreesFor.type [as addonTreesFor] (./node_modules/ember-cli/lib/broccoli/ember-app.js:523:30)
  at EmberApp._addonTree (./node_modules/ember-cli/lib/broccoli/ember-app.js:921:36)
  at EmberApp._notifyAddonIncluded.EmberApp.addonTreesFor.EmberApp.addonLintTree.EmberApp._podTemplatePatterns.EmberApp._processedVendorTree (./node_modules/ember-cli/lib/broccoli/ember-app.js:959:20)
  at EmberApp._notifyAddonIncluded.EmberApp.addonTreesFor.EmberApp.addonLintTree.EmberApp._podTemplatePatterns.EmberApp._processedExternalTree (./node_modules/ember-cli/lib/broccoli/ember-app.js:990:21)
  at EmberApp._notifyAddonIncluded.EmberApp.addonTreesFor.EmberApp.addonLintTree.EmberApp._podTemplatePatterns.EmberApp.appAndDependencies (./node_modules/ember-cli/lib/broccoli/ember-app.js:1099:23)
  at EmberApp._notifyAddonIncluded.EmberApp.addonTreesFor.EmberApp.addonLintTree.EmberApp._podTemplatePatterns.EmberApp.javascript (./node_modules/ember-cli/lib/broccoli/ember-app.js:1231:28)
  at EmberApp._notifyAddonIncluded.EmberApp.addonTreesFor.EmberApp.addonLintTree.EmberApp._podTemplatePatterns.EmberApp.javascript.EmberApp.styles.EmberApp.otherAssets.EmberApp._import.EmberApp.toArray (./node_modules/ember-cli/lib/broccoli/ember-app.js:1668:10)
  at EmberApp._notifyAddonIncluded.EmberApp.addonTreesFor.EmberApp.addonLintTree.EmberApp._podTemplatePatterns.EmberApp.javascript.EmberApp.styles.EmberApp.otherAssets.EmberApp._import.EmberApp.toTree (./node_modules/ember-cli/lib/broccoli/ember-app.js:1690:30)
  at module.exports (./ember-cli-build.js:65:14)
  at Builder.setupBroccoliBuilder (./node_modules/ember-cli/lib/models/builder.js:54:19)
  at new Builder (./node_modules/ember-cli/lib/models/builder.js:33:10)
  at ServeTask.run (./node_modules/ember-cli/lib/tasks/serve.js:15:19)
  at ./node_modules/ember-cli/lib/commands/serve.js:78:29
  at tryCatch (./node_modules/rsvp/dist/rsvp.js:539:12)
  at invokeCallback (./node_modules/rsvp/dist/rsvp.js:554:13)
  at ./node_modules/rsvp/dist/rsvp.js:629:16
  at flush (./node_modules/rsvp/dist/rsvp.js:2414:5)
  at nextTickCallbackWith0Args (node.js:436:9)
  at process._tickCallback (node.js:365:13)

```

</details>

**Comment by alexander-alvarez** [comment]
for posterity, I worked through this with @bbonnet by investigating some addons (most notably [`ember-modal-dialog`](https://github.com/yapplabs/ember-modal-dialog/tree/v1.0.0/app/styles/ember-modal-dialog) and lots of head scratching.

Auto Resolution:
- You should have `"ember-cli-sass": "*"` in your engine's `package.json`. It expects an `addon/styles/` folder and in this folder `addon/styles/addon.scss` will automatically be merged to your app tree (before your main repo's `app.scss` gets evaluated).

Manual Resolution:
- You can have `app/styles/bar.scss` and `app/styles/foo/bar.scss` if you want to manually import your styles into your `app.scss`, but you should not have `"ember-cli-sass": "*"` in your `package.json`. This enables you to define variables in your `app.scss` that you leverage in your addons as well conditionally let your consuming apps decide how to consume those styles.
```scss
// in app.scss
@import "foo"
@import "foo/bar"
```
