### ISSUE TITLE
When engines are set to lazy load, unit tests fail to run. 

### ISSUE THREAD

**Issue by MelSumner** [ember-engines/ember-engines#382]
QUnit tests are failing to run with a lazy-loaded engine. If lazy loading is turned off, tests are working as expected. 

Here is the error: 
Promise rejected after "it exists": Cannot read property 'subject' of undefined@ 43 ms 
Source: 	TypeError: Cannot read property 'subject' of undefined
    at _default.teardownSubject (http://localhost:4200/assets/test-support.js:15282:33)
    at http://localhost:4200/assets/test-support.js:14139:28
    at initializePromise (http://localhost:4200/assets/vendor.js:68358:5)
    at new Promise (http://localhost:4200/assets/vendor.js:68843:31)
    at nextStep (http://localhost:4200/assets/test-support.js:14138:20)
    at _default.invokeSteps (http://localhost:4200/assets/test-support.js:14145:16)
    at http://localhost:4200/assets/test-support.js:14103:25
    at tryCatch (http://localhost:4200/assets/vendor.js:68310:12)
    at invokeCallback (http://localhost:4200/assets/vendor.js:68322:13)
    at http://localhost:4200/assets/vendor.js:68391:7

**Comment by siva-sundar** [comment]
Have you tried by loading the engine assets with a `<script>` in your tests/index.html?

**Comment by majew7** [comment]
@siva-sundar Because your solution to this issue is similar to Issue https://github.com/ember-engines/ember-engines/issues/388, can you be more precise here too?

@MelSumner Did Siva's solution work for you?

**Comment by trentmwillis** [comment]
For more context on why this is happening, please see https://github.com/ember-engines/ember-engines/pull/453#issuecomment-317035825.

**Comment by amk221** [comment]
Also related: issue for adding documentation for this https://github.com/ember-engines/ember-engines/issues/496
