### ISSUE TITLE
Lazy loading with ember-browserify

### ISSUE THREAD

**Issue by thec0keman** [ember-engines/ember-engines#400]
First, thanks for all of the hard work on this project!  We are very excited to get our main application on ember engines

When using ember-browserify with a lazy loading engine, the following error is thrown during build:
```
Build failed.
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/engine-vendor.js] failed with:
Error: ENOENT: no such file or directory, open '/Users/thec0keman/sites/engine-test/tmp/source_map_concat-input_base_path-08yAXN4w.tmp/browserify/browserify.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at SourceMap.addFile (/Users/thec0keman/sites/engine-test/node_modules/fast-sourcemap-concat/lib/source-map.js:75:31)
    at /Users/thec0keman/sites/engine-test/node_modules/broccoli-concat/concat.js:200:16.
    at Array.forEach (native)
    at Concat.<anonymous> (/Users/thec0keman/sites/engine-test/node_modules/broccoli-concat/concat.js:198:24)
    at /Users/thec0keman/sites/engine-test/node_modules/fast-sourcemap-concat/lib/source-map.js:393:12
    at initializePromise (/Users/thec0keman/sites/engine-test/node_modules/rsvp/dist/rsvp.js:589:5)
    at new Promise$1 (/Users/thec0keman/sites/engine-test/node_modules/rsvp/dist/rsvp.js:1077:33)

The broccoli plugin was instantiated at:
    at Concat.Plugin (/Users/thec0keman/sites/engine-test/node_modules/broccoli-plugin/index.js:7:31)
    at new Concat (/Users/thec0keman/sites/engine-test/node_modules/broccoli-concat/concat.js:38:10)
    at module.exports (/Users/thec0keman/sites/engine-test/node_modules/broccoli-concat/index.js:26:10)
    at Class.buildVendorJSWithImports (/Users/thec0keman/sites/engine-test/node_modules/ember-engines/lib/engine-addon.js:194:7)
    at Class._memoize (/Users/thec0keman/sites/engine-test/node_modules/ember-engines/lib/utils/memoize.js:10:38)
    at Class.treeForPublic (/Users/thec0keman/sites/engine-test/node_modules/ember-engines/lib/engine-addon.js:657:59)
    at Class._treeFor (/Users/thec0keman/sites/engine-test/node_modules/ember-cli/lib/models/addon.js:517:33)
    at Class.treeFor (/Users/thec0keman/sites/engine-test/node_modules/ember-engines/lib/engine-addon.js:847:23)
    at project.addons.map.addon (/Users/thec0keman/sites/engine-test/node_modules/ember-cli/lib/broccoli/ember-app.js:525:20)
    at Array.map (native)
```

Everything works as expected when `lazyLoading: false`.

Example repo: https://github.com/thec0keman/ember-engine-browserify-test

(I can move or cross-post this to ember browserify if needed).

**Comment by thec0keman** [comment]
This was with:
Ember 2.12.1
Ember CLI 2.12.2
Ember Engines 0.5.2

**Comment by thec0keman** [comment]
After further investigation, this seems unrelated to ember-browserify.  After removing ember-browserify, this same issue came up with another engine dependency that also tried to push an npm dependency into the build.

I suspect there isn't anything special about the code, but here it is as an example: 
```
  included(app) {
    this._super.included.apply(this, arguments);

    // see: https://github.com/ember-cli/ember-cli/issues/3718
    while (typeof app.import !== 'function' && app.app) {
      app = app.app;
    }

    this.app = app;
    this.importBrowserDependencies(app);

    return app;
  },

  importBrowserDependencies(app) {
    if (arguments.length < 1) {
      throw new Error('Application instance must be passed to import');
    }

    var vendor = this.treePaths.vendor;
    var jplayerPath = vendor + '/jplayer/jquery.jplayer.min.js';

    app.import(jplayerPath);
  },

  treeForVendor(vendorTree) {
    var trees = [];
    var jplayerPath = path.dirname(require.resolve('jplayer'));

    if (vendorTree) {
      trees.push(vendorTree);
    }

    trees.push(new Funnel(jplayerPath, {
      destDir: 'jplayer',
    }));

    return mergeTrees(trees);
  }
```

This seems like a fairly standard approach to loading an NPM dependency, and it works just fine in the host app.  Is there a way this needs to be modified for an engine?

In this case I think we can extract this into a separate shim for the host app and not include it in the engine, and we should be okay. 🤞

**Comment by knownasilya** [comment]
I think the addon needs to use `this.import` instead.

**Comment by trentmwillis** [comment]
Last I can recall,` ember-engines` was incompatible with `ember-browserify` due to some weird build time interops. It was recommended to use [`ember-rollup`](https://www.npmjs.com/package/ember-rollup) instead (basically creates a rollup build to use in the browser).

**Comment by knownasilya** [comment]
@trentmwillis do you have an example with this being used/have you used it in an engine?

**Comment by trentmwillis** [comment]
We used it at LinkedIn, but I'm unsure if there is any open source example unfortunately. Before we enabled lazy loading we specifically removed all usage of `ember-browserify` from the app.

**Comment by knownasilya** [comment]
Would I pass `EngineAddon` into

```js
/* eslint-env node */
const emberRollup = require('ember-rollup');
const runtimeDependencies = ['my-module', 'rsvp'];
const EngineAddon = require('ember-engines/lib/engine-addon');

module.exports =  emberRollup(runtimeDependencies, EngineAddon.extend({
  name: 'dashboard',

  lazyLoading: true,

  isDevelopingAddon() {
    return true;
  }
}));
```

**Comment by trentmwillis** [comment]
I'm honestly unsure, @rwjblue maybe you can help/derive an example from LI?

**Comment by knownasilya** [comment]
I'm seeing this error:

```
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (vendor)] failed with:
Error: Merge error: conflicting capitalizations:
README.md in /Users/iradchenko/workspace/mapgeo2/map/tmp/broccoli_merge_trees-input_base_path-ZS7UThet.tmp/1
Readme.md in /Users/iradchenko/workspace/mapgeo2/map/tmp/broccoli_merge_trees-input_base_path-ZS7UThet.tmp/13
Remove one of the files and re-add it with matching capitalization.
We are strict about this to avoid divergent behavior between case-insensitive Mac/Windows and case-sensitive Linux.
    at MergeTrees._mergeRelativePath (/Users/iradchenko/workspace/mapgeo2/map/node_modules/merge-trees/index.js:193:19)
    at MergeTrees.merge (/Users/iradchenko/workspace/mapgeo2/map/node_modules/merge-trees/index.js:53:26)
    at BroccoliMergeTrees.build (/Users/iradchenko/workspace/mapgeo2/map/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:34:19)
    at /Users/iradchenko/workspace/mapgeo2/map/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/Users/iradchenko/workspace/mapgeo2/map/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/iradchenko/workspace/mapgeo2/map/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/iradchenko/workspace/mapgeo2/map/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/Users/iradchenko/workspace/mapgeo2/map/node_modules/rsvp/dist/rsvp.js:2400:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Which I thought might be related to #376, but #428 didn't help. Anyone have any ideas? cc @andrewfan

**Comment by knownasilya** [comment]
Cross-posted here: https://github.com/ember-cli/ember-cli/issues/4244
