### ISSUE TITLE
Engine not accessing models

### ISSUE THREAD

**Issue by fr0gs** [ember-engines/ember-engines#484]
I have an ember application running with ember-engines **0.5.12** and despite that it is properly mounted and I can access the engine from the parent application, when the engine's route is executed and the model is fetched, I consistently get:

```
ember.debug.js:18023 No model was found for 'docker-compose'
Error
    at Class._modelFactoryFor (http://localhost:4300/assets/vendor.js:93286:15)
    at Class._modelFor (http://localhost:4300/assets/vendor.js:93271:29)
    at Class.modelFor (http://localhost:4300/assets/vendor.js:93263:17)
    at _query (http://localhost:4300/assets/vendor.js:90145:26)
    at Class._query$$1 [as _query] (http://localhost:4300/assets/vendor.js:92524:27)
    at Class.query (http://localhost:4300/assets/vendor.js:92512:17)
    at Class.callee$0$0$ (http://localhost:4300/engines-dist/ember-stack-builder-engine/assets/engine.js:1988:38)
    at tryCatch (http://localhost:4300/assets/vendor.js:404:40)
    at Generator.invoke [as _invoke] (http://localhost:4300/assets/vendor.js:678:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:4300/assets/vendor.js:437:21)
    at Class._takeSafeStep (http://localhost:4300/engines-dist/ember-stack-builder-engine/assets/engine-vendor.js:3842:45)
    at Class._takeStep (http://localhost:4300/engines-dist/ember-stack-builder-engine/assets/engine-vendor.js:3857:33)
    at invokeWithOnError (http://localhost:4300/assets/vendor.js:11609:16)
    at Queue.flush (http://localhost:4300/assets/vendor.js:11670:9)
    at DeferredActionQueues.flush (http://localhost:4300/assets/vendor.js:11794:15)
    at Backburner.end (http://localhost:4300/assets/vendor.js:11864:23)
    at Backburner.run (http://localhost:4300/assets/vendor.js:11978:16)
    at Backburner._runExpiredTimers (http://localhost:4300/assets/vendor.js:12372:10)
    at Backburner._boundRunExpiredTimers (http://localhost:4300/assets/vendor.js:11833:11)
```

It seems that I would have to generate a model in the parent application for it to be able to deal with engines' models. This is somehow violating the isolation principles of the engines, and if those model implement some logic depending on additional code inside the engine, it is duplicating code and "piercing" the engine. 

Is this a known issue?

**Comment by neborn** [comment]
I am seeing this same issue. @fr0gs what was your resolution if any?

**Comment by fr0gs** [comment]
Moving the models to the wrapping application was the solution.

**Comment by akashdsouza** [comment]
You can instead move the models to the addon's app folder. This way, you wouldn't have to duplicate it in multiple wrapping apps.

**Comment by neborn** [comment]
That's what I was afraid of. Thanks Esteban and Akash.

**Comment by HelloMrBharath** [comment]
Models should maintain in parent application or we can maintain in Engine itself ?
