### ISSUE TITLE
Unknown object passed to sourceOfConfig() error

### ISSUE THREAD

**Issue by experfy-ismetbibic** [ember-engines/ember-engines#787]
Hello,
We're trying to incorporate ember-bootstrap addon in one of our engines, however we're running into some issues.
When starting the host app which has the engine mounted we're getting the following error:
`unknown object passed to sourceOfConfig(). You can only pass back the configs you were given.`

Seems like the issue is not on the ember-bootstrap side (https://github.com/kaliber5/ember-bootstrap/issues/1626) considering when downgrading the ember-engines version to `0.8.15` the error doesn't appear.

```
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: unknown object passed to sourceOfConfig(). You can only pass back the configs you were given.
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: unknown object passed to sourceOfConfig(). You can only pass back the configs you were given.
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: unknown object passed to sourceOfConfig(). You can only pass back the configs you were given.
    at /home/admin/Desktop/projects/frontend-core/node_modules/ember-engines/node_modules/@embroider/macros/src/macros-config.js:323:19
    at /home/admin/Desktop/projects/frontend-core/node_modules/ember-engines/node_modules/@embroider/macros/src/macros-config.js:315:76
    at arrayAggregator (/home/admin/Desktop/projects/frontend-core/node_modules/lodash/_arrayAggregator.js:17:32)
    at Object.default (/home/admin/Desktop/projects/frontend-core/node_modules/lodash/_createAggregator.js:19:12)
    at defaultMerger (/home/admin/Desktop/projects/frontend-core/node_modules/ember-engines/node_modules/@embroider/macros/src/macros-config.js:315:61)
    at MacrosConfig.get userConfigs [as userConfigs] (/home/admin/Desktop/projects/frontend-core/node_modules/ember-engines/node_modules/@embroider/macros/src/macros-config.js:182:55)
    at Object.get userConfigs [as userConfigs] (/home/admin/Desktop/projects/frontend-core/node_modules/ember-engines/node_modules/@embroider/macros/src/macros-config.js:210:29)
    at _clone (/home/admin/Desktop/projects/frontend-core/node_modules/clone/clone.js:162:31)
    at _clone (/home/admin/Desktop/projects/frontend-core/node_modules/clone/clone.js:162:18)
```

**Comment by jonchay** [comment]
We're seeing this issue as well, but we're not using `ember-bootstrap`.

**Comment by Maxhy** [comment]
I've got the same issue here but I cannot downgrade to @embroider/macros 0.42.3 as other dependencies requires upper versions...
I guess ember-engines needs to be updated to properly support new @embroider/macros versions?
Not sure if it is related but a breaking changes has been added on https://github.com/embroider-build/embroider/blob/7e5b1fe5398ed6b7ff81f4d65fabcbeac7b2930b/CHANGELOG.md#v0430-2021-07-13 ...

**Comment by Maxhy** [comment]
I fixed the issue by bumping ember-bootstrap and other dependencies to newer versions (and one downgrade). Definitely a @embroider/macros version mismatch issue between multiple dependencies ; but nothing specific to ember-engines to be fixed in practice indeed.
